# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'from3.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form3(object):
    def setupUi(self, Form3):
        Form3.setObjectName("Form3")
        Form3.resize(510, 370)
        self.textBrowser = QtWidgets.QTextBrowser(Form3)
        self.textBrowser.setGeometry(QtCore.QRect(0, 30, 510, 321))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Form3)
        QtCore.QMetaObject.connectSlotsByName(Form3)

    def retranslateUi(self, Form3):
        _translate = QtCore.QCoreApplication.translate
        Form3.setWindowTitle(_translate("Form3", "Form"))
        self.textBrowser.setHtml(_translate("Form3", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">这里是界面2这里是界面2这里是界面2这里是界面2这里是界面2这里是界面2这里是界面2这里是界面2这里是界面2这里是界面2这里是界面2这里是界面2这里是界面2这里是界面2这里是界面2这里是界面2</span></p></body></html>"))
